
## COMPANY.CRG_ID ##
CRG_ID_1=\uBC95\uC778\uC0AC\uC5C5\uC790
CRG_ID_2=\uAC1C\uC778\uC0AC\uC5C5\uC790

## COMPANY.CST_ID ##
CST_ID_1=\uB4F1\uB85D\uC644\uB8CC
CST_ID_2=\uB4F1\uB85D\uC2B9\uC778
CST_ID_3=\uD68C\uC6D0\uD0C8\uD1F4
CST_ID_12=\uC0AD\uC81C

# TAX_TYPE_
TAX_G=\uC77C\uBC18
TAX_S=\uC601\uC138</strong>
TAX_E=\uBA74\uC138</strong>
