sURL=http://210.112.124.64:31004/xerc/soaptoserver
kibo_sURL=http://210.112.124.3:7770/mps/Send/xmlKiboJavaToSend.jsp
kibo_yun_sURL=http://210.112.124.3:7770/mps/Send/xmlKoregJavaToSend.jsp
timeout=60000
dn-value=cn=\uC5E0\uD53C\uC6D0 \uC8FC\uC2DD\uD68C\uC0AC Server,ou=mp1,ou=SignKorea RA,o=SignKorea,c=KR
dn-password=gksckd0221!
