package kr.co.funology.fw.dev;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

import kr.co.funology.fw.GlobalEnv;
import kr.co.funology.fw.mgr.ConnectionMgr;

/**
 * Create DAO &amp; DTO.
 *
 *
 * @author DOLGAMZA
 *
 */
public class ModelBeanUtil {

	private String   strPackageClassName = null;
	private String   strQuery            = null;
	private String[] strColumnNames      = null;
	private String[] strColumnTypes      = null;
	private String   strResultMessage    = null;

	public ModelBeanUtil(String strClassNameString, String strQueryString) {
		strPackageClassName = strClassNameString;
		strQuery            = strQueryString;
		strResultMessage    = "";

		System.out.println(strPackageClassName);
		System.out.println(strQuery);

		if (setColumns() == true) {
			saveBeanClassFile();
			saveDaoClassFile();
		}
	}

	/**
	 * Set Column Types & Names
	 *
	 */
	private boolean setColumns() {
		boolean           isContinue   = true;
		ConnectionMgr     mgr          = ConnectionMgr.getInstance();
		Connection        conn         = mgr.getConnetion();
		PreparedStatement ps           = null;
		ResultSet         rs           = null;
		ResultSetMetaData rsmd         = null;
		try {
			ps = conn.prepareStatement(strQuery);
			rs = ps.executeQuery();
			rsmd = rs.getMetaData();
			strColumnTypes = new String[rsmd.getColumnCount()];
			strColumnNames = new String[rsmd.getColumnCount()];
			for (int i=1; i<=rsmd.getColumnCount(); i++) {
				strColumnTypes[i-1] = (rsmd.getColumnTypeName(i)!="int") ? "String" : "int";
				strColumnNames[i-1] = rsmd.getColumnLabel(i);
			}
			mgr.closeConnection(conn, ps, rs);
		} catch (SQLException e) {
			isContinue = false;
			e.printStackTrace();
		}
		return isContinue;
	}


	/**
	 * Save VO Class Source File
	 *
	 */
	private void saveBeanClassFile() {
		String   dir = GlobalEnv.getWebRootDir() + "\\src";
		String[] sa  = strPackageClassName.split("[.]");
		String   sf  = sa[sa.length-1] + "_BEAN.java";

		for (int i=0; i<sa.length-1; i++) {
			dir += "\\" + sa[i].replaceAll("dao", "vo");
		}

		try {
			saveFile(dir, sf, getBeanClassContent());
		} catch (IOException e) {
			strResultMessage += e.toString();
			e.printStackTrace();
		}
	}

	/**
	 * Get BEAN Class Source
	 *
	 * @return strBeanContent
	 */
	private StringBuffer getBeanClassContent() {
		StringBuffer      strBeanContent = new StringBuffer();
		String            str          = "";

		String[]          sa           = strPackageClassName.split("[.]");
		String            strClass     = sa[sa.length-1];
		str = "package " + sa[0];
		for (int i=1; i<sa.length-1; i++) {
			str += "." + sa[i].replaceAll("dao", "vo");
		}
		str += ";";

		strBeanContent.append(str + "\n\n");
		strBeanContent.append("/** " + strClass + "BEAN Class is Generated By ModelBeanUtil **/\n");
		strBeanContent.append("public class " + strClass + "_BEAN {\n");

		for (int i=0; i<strColumnTypes.length; i++) {
			strBeanContent.append("  private " + strColumnTypes[i] + " " + strColumnNames[i] + ";\n");
		}

		strBeanContent.append("\n\n");

		//setter�ۼ�
		strBeanContent.append("/** write setter **/\n");

		for (int i=0; i<strColumnTypes.length; i++) {
			String strMethodName = strColumnNames[i].substring(0, 1).toUpperCase()+strColumnNames[i].substring(1, strColumnNames[i].length()).toLowerCase();
			strBeanContent.append("  public void set"+ strMethodName + "(" + strColumnTypes[i] + " " + strColumnNames[i] + "){\n");
			strBeanContent.append("  this."+ strColumnNames[i] + " = " + strColumnNames[i] + ";\n");
			strBeanContent.append("  } \n");
		}

		strBeanContent.append("\n\n");

		//getter�ۼ�
		strBeanContent.append("/** write getter **/\n");

		for (int i=0; i<strColumnTypes.length; i++) {
			String strMethodName = strColumnNames[i].substring(0, 1).toUpperCase()+strColumnNames[i].substring(1, strColumnNames[i].length()).toLowerCase();
			strBeanContent.append("  public "+ strColumnTypes[i] +" get"+ strMethodName + "(){\n");
			strBeanContent.append("  return "+ strColumnNames[i] + ";\n");
			strBeanContent.append("  } \n");
		}

		strBeanContent.append("}\n");

		System.out.println(strBeanContent);
		return strBeanContent;
	}

	/**
	 * Save DAO Class Source File
	 *
	 */
	private void saveDaoClassFile() {
		String   dir = GlobalEnv.getWebRootDir() + "\\src";
		String[] sa  = strPackageClassName.split("[.]");
		String   sf  = sa[sa.length-1] + "DAO_BY_BEAN.java";

		for (int i=0; i<sa.length-1; i++) {
			dir += "\\" + sa[i];
		}

		try {
			saveFile(dir, sf, getDaoClassContent());
		} catch (IOException e) {
			strResultMessage += e.toString();
			e.printStackTrace();
		}
	}

	/**
	 * Get DAO Class Source
	 *
	 * @return strDaoContent
	 */
	private StringBuffer getDaoClassContent() {
		StringBuffer      strDaoContent = new StringBuffer();
		String            str           = "";
		String			  voStr			= "";

		String[]          sa            = strPackageClassName.split("[.]");
		String            strClass      = sa[sa.length-1];
		String            strFuncName   = ((" " + strQuery).split(" "))[(" " + strQuery).split(" ").length-1];

		// Set Package Name
		str = "package " + sa[0];
		for (int i=1; i<sa.length-1; i++) {
			str += "." + sa[i];
		}
		str += ";";

		strDaoContent.append(str + "\n");

		//	Set Vo import Name
		voStr = "\nimport " + sa[0];
		for (int i=1; i<sa.length-1; i++) {
			voStr += "." + sa[i].replaceAll("dao", "vo");
		}
		voStr += "." + strClass + "_BEAN;";


		// Set import
		strDaoContent.append("\nimport java.sql.Connection;");
		strDaoContent.append("\nimport java.sql.ResultSet;");
		strDaoContent.append("\nimport java.util.ArrayList;");
		strDaoContent.append("\nimport org.apache.log4j.Logger;");
		strDaoContent.append("\nimport kr.co.funology.fw.mgr.ConnectionMgr;");
		strDaoContent.append("\nimport kr.co.funology.fw.util.WrapPreparedStatementUtil;");
		strDaoContent.append("\n"+voStr);

		strDaoContent.append("\n\n/** " + strClass + "DAO BEAN Class is Generated By ModelBeanUtil **/");
		strDaoContent.append("\npublic class " + strClass + "DAO_BY_BEAN {\n");

		// Create Method
		strDaoContent.append("\n  public ArrayList " + strFuncName + "() {");
		strDaoContent.append("\n    Connection                conn = ConnectionMgr.getInstance().getConnetion();");
		strDaoContent.append("\n    WrapPreparedStatementUtil ps   = null;");
		strDaoContent.append("\n    ResultSet                 rs   = null;");
		strDaoContent.append("\n  	Logger logger = Logger.getLogger(this.getClass());");
		strDaoContent.append("\n    ArrayList vo = new ArrayList();");
		strDaoContent.append("\n    try {");
		strDaoContent.append("\n      ps = new WrapPreparedStatementUtil(conn, \" CALL " + strQuery + "\");");
		strDaoContent.append("\n      // TO-DO : Set Parameters. Ex) ps.setString(1, strUser);");
		strDaoContent.append("\n      ");
		strDaoContent.append("\n      ");
		strDaoContent.append("\n  	  logger.debug(ps.getQueryString());");
		strDaoContent.append("\n      rs = ps.executeQuery();");
		strDaoContent.append("\n      while(rs.next()) {");
		strDaoContent.append("\n\n/** Bean add**/");
		strDaoContent.append("\n        " + strClass + "_BEAN ent = new " + strClass + "_BEAN();");

		for (int i=0; i<strColumnTypes.length; i++) {
			String strMethodName = strColumnNames[i].substring(0, 1).toUpperCase()+strColumnNames[i].substring(1, strColumnNames[i].length()).toLowerCase();
			String strFunc = (strColumnTypes[i] == "int") ? "rs.getInt(\"" + strColumnNames[i] + "\")" : "rs.getString(\"" + strColumnNames[i] + "\")";
			strDaoContent.append("\n        ent.set" + strMethodName + "(" + strFunc + ");");
		}

		strDaoContent.append("\n        vo.add(ent);");
		strDaoContent.append("\n      }");
		strDaoContent.append("\n    } catch (Exception e) {");
		strDaoContent.append("\n  	  logger.error(ps.getQueryString());");
		strDaoContent.append("\n    } finally {");
		strDaoContent.append("\n  	  ConnectionMgr.getInstance().closeConnection(conn, ps, rs);");
		strDaoContent.append("\n    }");
		strDaoContent.append("\n    return vo;");
		strDaoContent.append("\n  }");
		strDaoContent.append("\n}");

		System.out.println(strDaoContent);
		return strDaoContent;
	}

	/**
	 * Save File
	 *
	 * @param strDir  Directory
	 * @param strFile FileName
	 * @param sb      To-Save Content
	 * @throws IOException
	 */
	private void saveFile(String strDir, String strFile, StringBuffer sb) throws IOException {
		File fdir = new File(strDir);
		File file = new File(fdir, strFile);

		if (fdir.exists() == false) {
			fdir.mkdirs();
		}

		if (file.exists() == false) {
			file.createNewFile();
		}

		FileWriter fw = new FileWriter(file);
		BufferedWriter bw = new BufferedWriter(fw);
		PrintWriter pw = new PrintWriter(bw, true);
		pw.println(sb);

		strResultMessage += file.getPath() + " is created successfully.<br>";

		pw.close();
		bw.close();
		fw.close();
	}

	/**
	 * Get Saved File Path.
	 *
	 * @return strResultMessage
	 */
	public String getResultMessage() {
		return strResultMessage;
	}

}
