INSERT INTO DBO.THIRDPARTY_TB (CD, NM, OWNERSHIP_RATE, LOGIN_ID, LOGIN_PW, USE_YN)
SELECT CD, NM, OWNERSHIP_RATE, LOGIN_ID, LOGIN_PW, USE_YN
  FROM [DOB2B-SERVER].[DOB2B].DBO.THIRDPARTY_TB


INSERT INTO DBO.THIRDPARTY_COMPANY_TB (CD, CPY_ID, CREATE_YMD, OWNERSHIP_RATE, SM_ID)
SELECT CD, CPY_ID, CREATE_YMD, OWNERSHIP_RATE, SM_ID
  FROM [DOB2B-SERVER].[DOB2B].DBO.THIRDPARTY_COMPANY_TB

INSERT INTO DBO.THIRDPARTY_COMPANY_BANK_TB (CPY_ID, BNK_CD)
SELECT CPY_ID, BNK_CD
  FROM [DOB2B-SERVER].[DOB2B].DBO.THIRDPARTY_COMPANY_BANK_TB


SET IDENTITY_INSERT THIRDPARTY_SALESMAN_TB OFF;

INSERT INTO DBO.THIRDPARTY_SALESMAN_TB (SM_ID, CD, SM_NM, REG_DT, USE_YN)
SELECT SM_ID, CD, SM_NM, REG_DT, USE_YN
  FROM [DOB2B-SERVER].[DOB2B].DBO.THIRDPARTY_SALESMAN_TB

SET IDENTITY_INSERT THIRDPARTY_SALESMAN_TB ON;