-- 2025년 3월 31일까지의 데이터를 가져온다.
-- 기본 코드데이터는 이미 적재되어 있다.
-- 매매계약과 관련된 데이터는 2020년 1월 1일부터 가져온다.
-- 최종데이터는 오픈직전에 적재되도록 쿼리를 수정하여 사용한다.

-- #001 세금계산서
SET IDENTITY_INSERT DBO.CT_BILL_MASTER ON;
INSERT INTO DBO.CT_BILL_MASTER (
    SBILL_SEQ
,	BILL_NO
,	APP_NO
,	BILL_DT
,	BILL_TYPE
,	BILL_GUBUN
,	SCOMP_VENDERNO
,	SCOMP_NAME
,	SCOMP_CEO
,	SCOMP_ADDRESS
,	SCOMP_TYPE
,	SCOMP_CLASS
,	RCOMP_VENDERNO
,	RCOMP_NAME
,	RCOMP_CEO
,	RCOMP_ADDRESS
,	RCOMP_TYPE
,	RCOMP_CLASS
,	PAY_SUM_AMOUNT
,	PAY_SUM_TAX
,	ITEM_NAME
,	DEL_YN
,	DEL_DATE
,	CPY_ID
,	REG_DATE
,	PAY_TAX_RATE
)
SELECT SBILL_SEQ
,	BILL_NO
,	APP_NO
,	BILL_DT
,	BILL_TYPE
,	BILL_GUBUN
,	SCOMP_VENDERNO
,	SCOMP_NAME
,	SCOMP_CEO
,	SCOMP_ADDRESS
,	SCOMP_TYPE
,	SCOMP_CLASS
,	RCOMP_VENDERNO
,	RCOMP_NAME
,	RCOMP_CEO
,	RCOMP_ADDRESS
,	RCOMP_TYPE
,	RCOMP_CLASS
,	PAY_SUM_AMOUNT
,	PAY_SUM_TAX
,	ITEM_NAME
,	DEL_YN
,	DEL_DATE
,	CPY_ID
,	REG_DATE
,	PAY_TAX_RATE
  FROM [DOB2B-SERVER].[DOB2B].DBO.CT_BILL_MASTER
 WHERE REG_DATE > '2019-01-01 00:00:00.000'
   AND REG_DATE < '2025-04-01 00:00:00.000';

SET IDENTITY_INSERT DBO.CT_BILL_MASTER OFF;

-- #002 세금계산서 아이템
INSERT INTO DBO.CT_BILL_ITEM (
       ITEM_SEQ
      ,SBILL_SEQ
      ,ITEM_NAME
      ,ITEM_PRICE
      ,ITEM_CNT
      ,ITEM_UNIT
      ,ITEM_AMOUNT
      ,ITEM_TAX
      ,ITEM_DT
)
SELECT ITEM_SEQ
      ,SBILL_SEQ
      ,ITEM_NAME
      ,ITEM_PRICE
      ,ITEM_CNT
      ,ITEM_UNIT
      ,ITEM_AMOUNT
      ,ITEM_TAX
      ,ITEM_DT
  FROM [DOB2B-SERVER].[DoB2B].[dbo].[CT_BILL_ITEM]
 WHERE SBILL_SEQ IN (SELECT SBILL_SEQ 
                       FROM DBO.CT_BILL_MASTER WITH (NOLOCK)
                      WHERE REG_DATE > '2019-01-01 00:00:00.000'
                        AND REG_DATE < '2025-04-01 00:00:00.000');
GO

-- #003 매매계약서
SET IDENTITY_INSERT DBO.CT_HEADER ON;
INSERT INTO DBO.CT_HEADER (
       CTID
     , CTNO
     , CTTYPE
     , DIRTYPE
     , TRADEDATE
     , CONTRACTDATE
     , CPYBUYER
     , CPYSELLER
     , TAXBIZTYPE
     , SUPPLYAMT
     , TAXAMT
     , TOTALCONTRACTAMT
     , MPPAYCPY
     , MPFEERATE
     , MPFEE_SUPPLYAMT
     , MPFEE_TAXAMT
     , MPFEE_TOTALAMT
     , PAY_ID
     , BNK_CD
     , MTYDATE
     , TRADETYPE
     , STATUS
     , REGUSER
     , REGTIME
     , SENDUSER
     , SENDTIME
     , LASTTIME
     , CHGREQ
     , CHGREQUSER
     , CHGREQTIME
     , CHGUSER
     , CHGTIME
     , CANUSER
     , CANTIME
     , APRUSER
     , APPRTIME
     , SGN_ID
     , SETTLEDATE
     , SETTLEAMT
     , SETTLEDUEDATE
     , CONFIRM_SETTLE_YN
     , TAXAPPROVALNO
     , REGDATE
     , SBILL_SEQ
     , BILL_DT
) 
SELECT A.CTID
     , A.CTNO
     , A.CTTYPE
     , A.DIRTYPE
     , A.TRADEDATE
     , A.CONTRACTDATE
     , A.CPYBUYER
     , A.CPYSELLER
     , A.TAXBIZTYPE
     , A.SUPPLYAMT
     , A.TAXAMT
     , A.TOTALCONTRACTAMT
     , A.MPPAYCPY
     , A.MPFEERATE
     , A.MPFEE_SUPPLYAMT
     , A.MPFEE_TAXAMT
     , A.MPFEE_TOTALAMT
     , A.PAY_ID
     , A.BNK_CD
     , A.MTYDATE
     , A.TRADETYPE
     , A.STATUS
     , A.REGUSER
     , A.REGTIME
     , A.SENDUSER
     , A.SENDTIME
     , A.LASTTIME
     , A.CHGREQ
     , A.CHGREQUSER
     , A.CHGREQTIME
     , A.CHGUSER
     , A.CHGTIME
     , A.CANUSER
     , A.CANTIME
     , A.APRUSER
     , A.APPRTIME
     , A.SGN_ID
     , A.SETTLEDATE
     , A.SETTLEAMT
     , A.SETTLEDUEDATE
     , A.CONFIRM_SETTLE_YN
     , A.TAXAPPROVALNO
     , LEFT(REGTIME, 8) AS REGDATE
	 , ISNULL(B.SBILL_SEQ, 0) AS SBILL_SEQ
	 , ISNULL(B.BILL_DT, '') AS BILL_DT
  FROM [DOB2B-SERVER].[DoB2B].[dbo].[CT_HEADER] A
  LEFT JOIN (SELECT MAX(SBILL_SEQ) AS SBILL_SEQ, APP_NO, BILL_DT 
               FROM [DOB2B-SERVER].[DoB2B].[dbo].[CT_BILL_MASTER]
			  WHERE USE_YN = 'Y'
			  GROUP BY APP_NO, BILL_DT
			  ) B
			  ON B.APP_NO = A.TAXAPPROVALNO
 WHERE A.REGTIME > '20200101000000'
   AND A.REGTIME < '20250401000000';
GO

SET IDENTITY_INSERT DBO.CT_HEADER OFF;
GO

-- #004 매매계약서의 품목정보
INSERT INTO DBO.CT_ITEM (
       [CTID]
      ,[SEQNO]
      ,[ITEMNAME]
      ,[QTY]
      ,[UNITPRICE]
      ,[UNIT]
      ,[SIZE]
      ,[SUPPLYAMT]
      ,[TAXAMT]
      ,[TOTALAMT]
)
SELECT [CTID]
      ,[SEQNO]
      ,[ITEMNAME]
      ,[QTY]
      ,[UNITPRICE]
      ,[UNIT]
      ,[SIZE]
      ,[SUPPLYAMT]
      ,[TAXAMT]
      ,[TOTALAMT]
  FROM [DOB2B-SERVER].[DoB2B].[dbo].[CT_ITEM]
 WHERE CTID IN (SELECT CTID 
                  FROM DBO.CT_HEADER WITH (NOLOCK)
				 WHERE REGTIME > '20200101000000'
                  AND REGTIME < '20250401000000');
GO

-- #005 서명정보
SET IDENTITY_INSERT DBO.SIGNINFO ON;
INSERT INTO DBO.SIGNINFO (SGN_ID, SGN_DESC, SGN_CREDATE)
SELECT SGN_ID
     , CASE WHEN CHARINDEX('$DATA', SGN_DESC)-1 > 0 THEN LEFT(LEFT(SGN_DESC, CHARINDEX('$DATA', SGN_DESC)-1), 100) ELSE LEFT(SGN_DESC, 150) END
     , SGN_CREDATE
  FROM [DOB2B-SERVER].[DoB2B].DBO.SIGNINFO
 WHERE SGN_CREDATE > '2019-01-01 00:00:00.000'
   AND SGN_CREDATE < '2025-04-01 00:00:00.000';
SET IDENTITY_INSERT DBO.SIGNINFO OFF;
GO

-- #006 서명정보 및 아이피, 스크랩정보 업데이트
UPDATE A
   SET A.CU_USE_YN      = ISNULL(B.CU_USE_YN, 'N')
     , A.BUYER_IP       = B.BUYER_IP
	 , A.SELLER_IP      = B.SELLER_IP
	 , A.SELLER_APP_SGN_ID  = B.SELLER_APP_SGN_ID
  FROM DBO.CT_HEADER A
  JOIN [DOB2B-SERVER].[DoB2B].[dbo].CT_HEADER_ETC B ON A.CTID = B.CTID
 WHERE REGTIME > '20200101000000'
   AND REGTIME < '20250401000000';
GO

-- #007 상담내역
SET IDENTITY_INSERT DBO.ACTIVE_MANAGEMENT ON;
INSERT INTO DBO.ACTIVE_MANAGEMENT (
       ACTIVE_ID
     , ACTIVE_KIND
     , WRITE_ID
     , WRITE_DATE
     , CPY_ID
     , CALL_TYPE
     , ACTIVE_DESC
       )
SELECT ACTIVE_ID
     , ACTIVE_KIND
     , WRITE_ID
     , WRITE_DATE
     , CPY_ID
     , CALL_TYPE
     , ACTIVE_DESC
  FROM [DOB2B-SERVER].[DoB2B].[dbo].ACTIVE_MANAGEMENT
 WHERE WRITE_DATE < '2025-04-01 00:00:00.000';
GO
SET IDENTITY_INSERT DBO.ACTIVE_MANAGEMENT OFF;
GO

-- #008 동일사업장이상거래예외

INSERT INTO DBO.ADDRESS_EXEMPT_COMPANY (
SEQNO,
CPYBUYER,
CPYSELLER,
USE_YN,
CRETIME,
CREUSER,
LASTTIME,
LASTUSER,
UNUSUAL_SEQNO,
PRO_RESULT,
LOANTYPE,
ETC
) 
SELECT
SEQNO,
CPYBUYER,
CPYSELLER,
USE_YN,
CRETIME,
CREUSER,
LASTTIME,
LASTUSER,
UNUSUAL_SEQNO,
PRO_RESULT,
LOANTYPE,
ETC
FROM [DOB2B-SERVER].[DoB2B].DBO.ADDRESS_EXEMPT_COMPANY
WHERE SEQNO NOT IN (SELECT SEQNO FROM DBO.ADDRESS_EXEMPT_COMPANY);
GO

-- #009 BUSINESS_PERSON
SELECT * FROM DBO.BUSINESS_PERSON


INSERT INTO DBO.BUSINESS_PERSON (
       CPY_ID
	 , BUY_CPY_ID
	 , PRS_ID
	 , USE_YN
       )
SELECT B.CPY_ID
     , B.BUY_CPY_ID
	 , B.PRS_ID
	 , 'Y'
  FROM [DOB2B-SERVER].[DOB2B].DBO.BUSINESS_PERSON B WITH (NOLOCK)
 WHERE B.USE_YN = 'Y'
   AND NOT EXISTS (
        SELECT 1
        FROM DBO.BUSINESS_PERSON BP WITH (NOLOCK)
        WHERE BP.CPY_ID = B.CPY_ID
          AND BP.BUY_CPY_ID = B.BUY_CPY_ID
          AND BP.PRS_ID = B.PRS_ID
)
 GROUP BY B.CPY_ID,
       B.BUY_CPY_ID,
       B.PRS_ID;
GO

-- #010 COMPANY_NO_TRADE
INSERT INTO DBO.COMPANY_NO_TRADE (
       BUYER_BIZ_NO
     , BUYER_NAME
     , SELLER_BIZ_NO
     , SELLER_NAME
     , ETC
     , DEL_YN
	   )
SELECT 
    B.BUYER_BIZ_NO,
    B.BUYER_NAME,
    B.SELLER_BIZ_NO,
    B.SELLER_NAME,
    B.ETC,
    B.DEL_YN
FROM [DOB2B-SERVER].[DoB2B].[dbo].[COMPANY_NO_TRADE] B
WHERE NOT EXISTS (
    SELECT 1
    FROM DBO.COMPANY_NO_TRADE A WITH (NOLOCK)
    WHERE A.BUYER_BIZ_NO = B.BUYER_BIZ_NO
      AND A.SELLER_BIZ_NO = B.SELLER_BIZ_NO
);
GO

-- #011 COMPANY_RELATION_EXCEPT
INSERT INTO DBO.COMPANY_RELATION_EXCEPT (
       CPY_BUYER
     , CPY_SELLER
     , EXCEPT_YN
     , MEMO
     , REG_USER
     , REG_TIME
     , CAN_USER
     , CAN_TIME
	   )
SELECT 
    B.CPY_BUYER,
    B.CPY_SELLER,
    B.EXCEPT_YN,
    B.MEMO,
    B.REG_USER,
    B.REG_TIME,
    B.CAN_USER,
    B.CAN_TIME
FROM [DOB2B-SERVER].[DoB2B].[dbo].[COMPANY_RELATION_EXCEPT] B
WHERE NOT EXISTS (
    SELECT 1
    FROM DBO.COMPANY_RELATION_EXCEPT A WITH (NOLOCK)
    WHERE A.CPY_BUYER = B.CPY_BUYER
      AND A.CPY_SELLER = B.CPY_SELLER
);
GO


-- #012 COMPANY_SALES
INSERT INTO DBO.COMPANY_SALES (
       CPY_ID
     , YYYY
     , SALES_AMT
     , CREUSER
     , CREDATE
	   )
SELECT CPY_ID
     , YYYY
     , SALES_AMT
     , CREUSER
     , CREDATE
  FROM [DOB2B-SERVER].[DoB2B].[dbo].[COMPANY_SALES]
 WHERE CREDATE < '20250401';
GO

SET IDENTITY_INSERT DBO.COMPANY ON;
GO

-- #013 COMPANY

INSERT INTO DBO.COMPANY (
       CPY_ID
     , CRG_ID
     , CST_ID
     , CPY_NAME
     , CPY_FAX
     , CPY_BUSINESS_DESC
     , CPY_BUSINESS_NO
     , CPY_INCORPORATE_NO
     , CPY_CEO_NAME
     , CPY_CREDATE
     , CPY_VALIDATE
     , CPY_FOUNDYEAR
     , CPY_GUBUN
     , MP_CODE
     , CPY_DISHONOR
     , CONFIRM_SETTLE_YN
	   )
SELECT CPY_ID
     , CRG_ID
     , CST_ID
     , CPY_NAME
     , CPY_FAX
     , CPY_BUSINESS_DESC
     , CPY_BUSINESS_NO
     , CPY_INCORPORATE_NO
     , CPY_CEO_NAME
     , CPY_CREDATE
     , CPY_VALIDATE
     , CPY_FOUNDYEAR
     , CPY_GUBUN
     , MP_CODE
     , (CASE WHEN CPY_DISHONOR IS NULL THEN 0 ELSE CPY_DISHONOR END) AS CPY_DISHONOR
     , CONFIRM_SETTLE_YN
  FROM [DOB2B-SERVER].[DoB2B].[dbo].[COMPANY]
 WHERE CPY_ID NOT IN (SELECT CPY_ID FROM DBO.COMPANY WITH (NOLOCK));
 GO

 SET IDENTITY_INSERT DBO.COMPANY OFF;
 GO

-- #014 COMPANY (BUSINESS_TYPE, INDUSTRY)

UPDATE A
   SET A.BUSINESS_TYPE = LEFT(B.CPY_BUSINESS_TYPE, 25)
     , A.INDUSTRY      = B.CPY_CATEGORY
  FROM DBO.COMPANY A
  JOIN [DOB2B-SERVER].[DoB2B].[dbo].COMPANY_ADD B ON A.CPY_ID = B.CPY_ID
 WHERE A.BUSINESS_TYPE IS NULL;
GO

-- #015 COMPANY (ADDRESS)

UPDATE E
   SET E.CPY_ZIPCODE = D.ADR_ZIPCODE
     , E.CPY_ADDR    = D.ADR_DESC
     , E.CPY_ADDR2   = ADR_DESC2
  FROM DBO.COMPANY E
 INNER JOIN (
SELECT C.CPY_ID
     , REPLACE(ISNULL(ADR_ZIPCODE, ''), '-', '') AS ADR_ZIPCODE
     , REPLACE(REPLACE(ISNULL(ADR_DESC, ''), '&nbsp;', ' '), '&nbsp', '') AS ADR_DESC
	 , ISNULL(ADR_DESC2, '') AS ADR_DESC2
  FROM [DOB2B-SERVER].[DoB2B].[dbo].[ADDRESS] A
 INNER JOIN [DOB2B-SERVER].[DoB2B].[dbo].[COMPANY] C ON C.ADR_ID = A.ADR_ID
       ) D ON D.CPY_ID = E.CPY_ID
 WHERE E.CPY_ZIPCODE IS NULL;
GO

UPDATE DBO.COMPANY
   SET CPY_ADDR = LEFT(RTRIM(CPY_ADDR), LEN(RTRIM(CPY_ADDR)) - 1)
WHERE RIGHT(RTRIM(CPY_ADDR), 1) = ',';
GO

UPDATE DBO.COMPANY
   SET CPY_ADDR2 = RTRIM(LTRIM(CPY_ADDR2))
WHERE RIGHT(RTRIM(CPY_ADDR), 1) = ',';
GO

-- #015 COMPANY (SIGN_EXCLUDE_YN)
UPDATE DBO.COMPANY SET SIGN_EXCLUDE_YN = 'N' WHERE SIGN_EXCLUDE_YN = 'Y';
GO

UPDATE DBO.COMPANY 
   SET SIGN_EXCLUDE_YN = 'Y'
 WHERE CPY_ID IN (SELECT A.CPY_ID 
                    FROM [DOB2B-SERVER].[DoB2B].[dbo].SELLER_SIGN_EXCEPTION A WITH (NOLOCK)
                   INNER JOIN (SELECT CPY_ID, MAX(SEQ) AS SEQ FROM  [DOB2B-SERVER].[DoB2B].[dbo].SELLER_SIGN_EXCEPTION WITH (NOLOCK) WHERE USE_YN='Y' GROUP BY CPY_ID) B
                      ON A.CPY_ID = B.CPY_ID
                     AND A.SEQ = B.SEQ
                   WHERE A.USE_YN = 'Y'
                     AND EXCEPTION_YN = 'Y');
GO
-- 85

-- #016 COMPANY (CU_USE_YN)
UPDATE DBO.COMPANY SET CU_USE_YN = 'N' WHERE CU_USE_YN = 'Y';
GO

UPDATE DBO.COMPANY 
   SET CU_USE_YN = 'Y'
 WHERE CPY_ID IN (SELECT CPY_ID
                    FROM [DOB2B-SERVER].[DoB2B].[dbo].COMPANY_ADD
                   WHERE CU_USE_YN = 'Y');
GO
-- 25

-- #017 COMPANY (CPY_MEMO)
UPDATE DBO.COMPANY SET CPY_MEMO = NULL WHERE CPY_MEMO IS NOT NULL;
GO

UPDATE E
   SET E.CPY_MEMO = A.CPY_MEMO
  FROM DBO.COMPANY E
 INNER JOIN (SELECT CPY_ID 
                  , CPY_MEMO
               FROM [DOB2B-SERVER].[DoB2B].[dbo].COMPANY_ADD
              WHERE CPY_MEMO IS NOT NULL) A ON A.CPY_ID = E.CPY_ID;
GO
-- 3127

-- #018 COMPANY (REVERSE_YN)
UPDATE DBO.COMPANY SET REVERSE_YN = 'N' WHERE REVERSE_YN = 'Y';
GO

UPDATE DBO.COMPANY 
   SET REVERSE_YN = 'Y'
 WHERE CPY_ID IN (SELECT CPY_SELLER
                    FROM [DOB2B-SERVER].[DoB2B].[dbo].RECONTRACT_RELATION WITH (NOLOCK)
                   WHERE USE_YN = 'Y');
-- 770

-- #018 COMPANY (DIRECT_RELATION)
DELETE FROM DBO.DIRECT_RELATION;
GO

INSERT INTO DBO.DIRECT_RELATION (
       SELL_COMPANY
     , BUY_COMPANY
     , EXPIRE_DAY
     , CREATE_DATE
     , USE_YN
     , AGREE_YN
     , AGREE_DATE
	   )
SELECT SELL_COMPANY
     , BUY_COMPANY
     , EXPIRE_DAY
     , CREATE_DATE
     , USE_YN
     , AGREE_YN
     , AGREE_DATE
  FROM [DOB2B-SERVER].[DoB2B].[dbo].DIRECT_RELATION
 WHERE USE_YN = 'Y';
GO

-- #019 COMPANY_MPFEE_INFO_TB

DELETE FROM DBO.COMPANY_MPFEE_INFO_TB;
GO

INSERT INTO DBO.COMPANY_MPFEE_INFO_TB (
  CPY_ID
, BIZNO
, BIZNM
, CEONM
, BUSINESS_TYPE
, INDUSTRY
, ZIPCODE
, ADDR
, ADDR2
, REG_ID
, REG_DT
, USE_YN
       )
SELECT A.CPY_ID
     , A.MPTAX_BIZNO AS BIZNO
	 , A.MPTAX_BIZNAME AS BIZNM
	 , LEFT(A.MPTAX_CEONAME, 10) AS CEONM
	 , LEFT(A.CPY_BUSINESS_TYPE, 25) AS BUSINESS_TYPE
	 , A.CPY_CATEGORY AS INDUSTRY
	 , REPLACE(ISNULL(A.MPTAX_ZIPCODE, ''), '-', '') AS ZIPCODE
	 , A.MPTAX_ADDR AS ADDR
	 , A.MPTAX_ADDR2 AS ADDR2
	 , A.CREUSER AS REG_ID
	 , ISNULL(C.CPY_CREDATE, GETDATE()) AS REG_DT
	 , 'Y' AS USE_YN
  FROM [DOB2B-SERVER].[DoB2B].[dbo].COMPANY_ADD A
 INNER JOIN DBO.COMPANY C WITH (NOLOCK) ON C.CPY_ID = A.CPY_ID
 WHERE A.MPTAX_BIZNO IS NOT NULL;
GO

-- #020 CT_MYCOMPANY
DELETE FROM DBO.CT_MYCOMPANY;
GO

INSERT INTO DBO.CT_MYCOMPANY (CPY_ID, MY_CPY_ID, REMOTE_ADDR, REG_DT, TAX_SECTION)
SELECT A.CPY_ID, MY_CPY_ID, REMOTE_ADDR, REG_DT, TAX_SECTION
  FROM [DOB2B-SERVER].[DoB2B].[dbo].CT_MYCOMPANY A
 INNER JOIN DBO.COMPANY C WITH (NOLOCK) ON C.CPY_ID = A.CPY_ID;
GO
--154938

-- #021 GUARANTEE_MASTER_INFO
DELETE FROM DBO.GUARANTEE_MASTER_INFO;
GO

INSERT INTO DBO.GUARANTEE_MASTER_INFO (
       CPY_ID
     , BNK_CD
     , PAY_ID
     , CPY_GUAR_SEQ
     , GUAR_LOC
     , GUAR_STATUS
     , GUAR_CRA_DATE
     , GUAR_EXP_DATE
     , GUAR_VAL_DATE
     , GUAR_TOTAL_AMT
     , MEMO
     , WRITE_DATE
     , WRITE_ID
     , MODIFY_DATE
     , MODIFY_ID
     , DEL_DATE
     , DEL_ID
     , DEL_YN
     , BANK_LOC_DESC
	   )
SELECT CPY_ID
     , BNK_CD
     , PAY_ID
     , CPY_GUAR_SEQ
     , GUAR_LOC
     , GUAR_STATUS
     , GUAR_CRA_DATE
     , GUAR_EXP_DATE
     , GUAR_VAL_DATE
     , GUAR_TOTAL_AMT
     , MEMO
     , WRITE_DATE
     , WRITE_ID
     , MODIFY_DATE
     , MODIFY_ID
     , DEL_DATE
     , DEL_ID
     , DEL_YN
     , BANK_LOC_DESC
  FROM [DOB2B-SERVER].[DoB2B].[dbo].[GUARANTEE_MASTER_INFO]
 WHERE WRITE_DATE < '2025-04-01 00:00:00'
   AND CPY_ID IN (SELECT CPY_ID FROM DBO.COMPANY WITH (NOLOCK));
GO

-- #022 MAST_OFF_COMMISSION

SET IDENTITY_INSERT DBO.MAST_OFF_COMMISSION ON;
GO

INSERT INTO DBO.MAST_OFF_COMMISSION (
       CPY_ID
     , SEQNO
     , END_MONEY
     , RECEIVE_DATE
     , WRITE_ID
     , WRITE_DATE
     , MODIFY_ID
     , MODIFY_DATE
     , DEL_YN
     , START_DT
     , END_DT
     , COMM_ID
     , COMM_METHOD
     , A.CTNO
     , B.CTID
       )
SELECT CPY_ID
     , SEQNO
     , END_MONEY
     , RECEIVE_DATE
     , WRITE_ID
     , WRITE_DATE
     , MODIFY_ID
     , MODIFY_DATE
     , DEL_YN
     , START_DT
     , END_DT
     , COMM_ID
     , COMM_METHOD
     , A.CTNO
     , B.CTID
  FROM [DOB2B-SERVER].[DoB2B].[dbo].[MAST_OFF_COMMISSION] A
 INNER JOIN DBO.CT_HEADER B WITH (NOLOCK) ON B.CTNO = A.CTNO
 WHERE B.CTID NOT IN (SELECT CTID FROM DBO.MAST_OFF_COMMISSION WITH (NOLOCK));
GO

SET IDENTITY_INSERT DBO.MAST_OFF_COMMISSION OFF;
GO

-- #023 PERSON

SET IDENTITY_INSERT DBO.PERSON ON;
GO

INSERT INTO DBO.PERSON (
       PRS_ID
     , CPY_ID
     , PRS_NAME
     , PRS_TEL
     , PRS_LOGIN
     , PRS_PASSWD
     , PRS_EMAIL
     , PRS_MOBILE_NO
     , PRS_SMS
       )
SELECT PRS_ID
     , CPY_ID
     , PRS_NAME
     , PRS_TEL
     , PRS_LOGIN
     , PRS_PASSWD
     , PRS_EMAIL
     , PRS_MOBILE_NO
     , PRS_SMS
  FROM [DOB2B-SERVER].[DoB2B].[dbo].PERSON A
 WHERE PRS_LOGIN IS NOT NULL 
   AND PRS_LOGIN <> ''
   AND CPY_ID NOT IN (SELECT CPY_ID FROM DBO.PERSON WITH (NOLOCK));
GO

SET IDENTITY_INSERT DBO.PERSON OFF;
GO

-- #023 RELATION_COMPANY

SET IDENTITY_INSERT DBO.RELATION_COMPANY ON;
GO

INSERT INTO DBO.RELATION_COMPANY (
       SEQNO
     , CPY_ID
     , RELATIONBIZNO
     , USE_YN
     , CRETIME
     , CREUSER
     , LASTTIME
     , LASTUSER
     , UNUSUAL_SEQNO
     , PRO_RESULT
     , LOANTYPE
     , ETC
	   )
SELECT SEQNO
     , CPY_ID
     , RELATIONBIZNO
     , USE_YN
     , CRETIME
     , CREUSER
     , LASTTIME
     , LASTUSER
     , UNUSUAL_SEQNO
     , PRO_RESULT
     , LOANTYPE
     , ETC
  FROM [DOB2B-SERVER].[DoB2B].[dbo].RELATION_COMPANY WITH (NOLOCK)
 WHERE SEQNO NOT IN (SELECT SEQNO FROM DBO.RELATION_COMPANY WITH (NOLOCK));
GO

SET IDENTITY_INSERT DBO.RELATION_COMPANY OFF;
GO

-- #024 SEPARATION_ACCOUNT_TB

INSERT INTO DBO.SEPARATION_ACCOUNT_TB (
       CPY_ID
     , PRS_ID
     , PRS_NAME
     , PRS_TEL
     , PRS_EMAIL
     , PRS_MOBILE_NO
       )
SELECT CPY_ID
     , PRS_ID
     , PRS_NAME
     , PRS_TEL
     , PRS_EMAIL
     , PRS_MOBILE_NO
  FROM [DOB2B-SERVER].[DoB2B].[dbo].SEPARATION_ACCOUNT_TB WITH (NOLOCK)
 WHERE PRS_ID IN (SELECT PRS_ID FROM DBO.PERSON WITH (NOLOCK))
   AND PRS_ID NOT IN (SELECT PRS_ID FROM DBO.SEPARATION_ACCOUNT_TB WITH (NOLOCK));
GO

-- #025 INFO_COMMISSION

SET IDENTITY_INSERT DBO.INFO_COMMISSION ON;
GO

INSERT INTO DBO.INFO_COMMISSION (
       COMM_ID
     , CPY_BUYER
     , CPY_SELLER
     , PAY_CPY
     , COMM_CPY
     , PAY_GUBUN
     , COMM_METHOD
     , STD_DAYS
     , MTY_STDAYS
     , MTY_ENDDAYS
     , CPY_COMMISSION_RATE1
     , CPY_COMMISSION_RATE2
     , DISCOUNT_RATE
     , IN_CONFIRM_YN
     , COMM_DESC
     , USE_YN
     , CREDATE
     , CPY_COMMISSION_RATE
     , RECEIVE_MONEY
     , OFFLINE_YN
     , MAX_YN
     , MODDATE
     , MODID
	   )
SELECT COMM_ID
     , CPY_BUYER
     , CPY_SELLER
     , PAY_CPY
     , COMM_CPY
     , PAY_GUBUN
     , COMM_METHOD
     , STD_DAYS
     , MTY_STDAYS
     , MTY_ENDDAYS
     , CPY_COMMISSION_RATE1
     , CPY_COMMISSION_RATE2
     , DISCOUNT_RATE
     , IN_CONFIRM_YN
     , COMM_DESC
     , USE_YN
     , CREDATE
     , CPY_COMMISSION_RATE
     , RECEIVE_MONEY
     , OFFLINE_YN
     , MAX_YN
     , MODDATE
     , MODID
  FROM [DOB2B-SERVER].[DoB2B].[dbo].INFO_COMMISSION
 WHERE COMM_ID NOT IN (SELECT COMM_ID FROM DBO.INFO_COMMISSION WITH (NOLOCK))
GO

SET IDENTITY_INSERT DBO.INFO_COMMISSION OFF;
GO

-- #026 SEND_XML_B311

INSERT INTO DBO.SEND_XML_B311 (
       CTID
     , ORDERNO
     , FUND
     , SEQNO
     , RECEIVER
     , TRANSACTIONSEQNO
     , TRANSACTIONNO
     , TRANSACTIONDATE
     , TRANSACTIONTIME
     , RESPONSECODE
     , RESPONSEMSG
     , RESRESPONSECODE
     , RESRESPONSEMSG
       )
SELECT C.CTID
     , X.ORDERNO
     , 'KODIT' AS FUND
     , X.SEQNO
     , X.RECEIVER
     , X.TRANSACTIONSEQNO
     , X.TRANSACTIONNO
     , X.TRANSACTIONDATE
     , X.TRANSACTIONTIME
     , X.RESPONSECODE
     , X.RESPONSEMESSAGE AS RESPONSEMSG
     , X.RESRESPONSECODE
     , X.RESRESPONSEMESSAGE AS RESRESPONSEMSG
  FROM [DOB2B-SERVER].[DoB2B].[dbo].KODIT_XML_B311 X WITH (NOLOCK)
 INNER JOIN DBO.CT_HEADER C WITH (NOLOCK) ON C.CTNO = X.ORDERNO
 WHERE C.CTID NOT IN (SELECT CTID FROM DBO.SEND_XML_B311 WITH (NOLOCK));
 GO

 INSERT INTO DBO.SEND_XML_B311 (
       CTID
     , ORDERNO
     , FUND
     , SEQNO
     , RECEIVER
     , TRANSACTIONSEQNO
     , TRANSACTIONNO
     , TRANSACTIONDATE
     , TRANSACTIONTIME
     , RESPONSECODE
     , RESPONSEMSG
     , RESRESPONSECODE
     , RESRESPONSEMSG
       )
SELECT C.CTID
     , X.ORDERNO
     , 'KIBO' AS FUND
     , X.SEQNO
     , X.RECEIVER
     , X.TRANSACTIONSEQNO
     , X.TRANSACTIONNO
     , X.TRANSACTIONDATE
     , X.TRANSACTIONTIME
     , X.RESPONSECODE
     , X.RESPONSEMESSAGE AS RESPONSEMSG
     , X.RESRESPONSECODE
     , X.RESRESPONSEMESSAGE AS RESRESPONSEMSG
  FROM [DOB2B-SERVER].[DoB2B].[dbo].KIBO_XML_B311 X WITH (NOLOCK)
 INNER JOIN DBO.CT_HEADER C WITH (NOLOCK) ON C.CTNO = X.ORDERNO
 WHERE C.CTID NOT IN (SELECT CTID FROM DBO.SEND_XML_B311 WITH (NOLOCK));
 GO

-- #027 RECEIVE_XML_K311

INSERT INTO DBO.RECEIVE_XML_K311 (
       ORDERNO
     , SEQNO
     , FUND
     , SENDER
     , TRANSACTIONSEQNO
     , RECEIVER
     , TRANSACTIONNO
     , TRANSACTIONDATE
     , TRANSACTIONTIME
     , RESPONSECODE
     , RESPONSEMESSAGE
     , USERFIELD
     , TRADEDATE
     , CONTRACTDATE
     , SETTLEMANTDUEAMT
     , SETTLEAMT
     , PAYMENTAMT
     , REFUNDAMT
     , SETTLEMENTDUEDATE
     , BUYERFEE
     , SELLERFEE
     , RESSENDER
     , RESTRANSACTIONSEQNO
     , RESRECEIVER
     , RESTRANSACTIONNO
     , RESTRANSACTIONDATE
     , RESUSERFIELD
     , RESTRANSACTIONTIME
     , RESRESPONSECODE
     , RESRESPONSEMESSAGE
     , RESORDERNO
     , RESCONTRACTDATE

       )
SELECT ORDERNO
     , SEQNO
     , 'KODIT' AS FUND
     , SENDER
     , TRANSACTIONSEQNO
     , RECEIVER
     , TRANSACTIONNO
     , TRANSACTIONDATE
     , TRANSACTIONTIME
     , RESPONSECODE
     , RESPONSEMESSAGE
     , USERFIELD
     , X.TRADEDATE
     , X.CONTRACTDATE
     , SETTLEMENTDUEAMT AS SETTLEMANTDUEAMT
     , SETTLEMENTAMT AS SETTLEAMT
     , PAYMENTAMT
     , REFUNDAMT
     , SETTLEMENTDUEDATE
     , BUYERFEE
     , SELLERFEE
     , RESSENDER
     , RESTRANSACTIONSEQNO
     , RESRECEIVER
     , RESTRANSACTIONNO
     , RESTRANSACTIONDATE
     , RESUSERFIELD
     , RESTRANSACTIONTIME
     , RESRESPONSECODE
     , RESRESPONSEMESSAGE
     , RESORDERNO
     , RESCONTRACTDATE
  FROM [DOB2B-SERVER].[DoB2B].[dbo].KODIT_XML_K311 X WITH (NOLOCK)
 INNER JOIN DBO.CT_HEADER C WITH (NOLOCK) ON C.CTNO = X.ORDERNO
 WHERE C.CTNO NOT IN (SELECT ORDERNO FROM DBO.RECEIVE_XML_K311 WITH (NOLOCK));
GO

INSERT INTO DBO.RECEIVE_XML_K311 (
       ORDERNO
     , SEQNO
     , FUND
     , SENDER
     , TRANSACTIONSEQNO
     , RECEIVER
     , TRANSACTIONNO
     , TRANSACTIONDATE
     , TRANSACTIONTIME
     , RESPONSECODE
     , RESPONSEMESSAGE
     , USERFIELD
     , TRADEDATE
     , CONTRACTDATE
     , SETTLEMANTDUEAMT
     , SETTLEAMT
     , PAYMENTAMT
     , REFUNDAMT
     , SETTLEMENTDUEDATE
     , BUYERFEE
     , SELLERFEE
     , RESSENDER
     , RESTRANSACTIONSEQNO
     , RESRECEIVER
     , RESTRANSACTIONNO
     , RESTRANSACTIONDATE
     , RESUSERFIELD
     , RESTRANSACTIONTIME
     , RESRESPONSECODE
     , RESRESPONSEMESSAGE
     , RESORDERNO
     , RESCONTRACTDATE

       )
SELECT ORDERNO
     , SEQNO
     , 'KIBO' AS FUND
     , SENDER
     , TRANSACTIONSEQNO
     , RECEIVER
     , TRANSACTIONNO
     , TRANSACTIONDATE
     , TRANSACTIONTIME
     , RESPONSECODE
     , RESPONSEMESSAGE
     , USERFIELD
     , X.TRADEDATE
     , X.CONTRACTDATE
     , SETTLEMENTDUEAMT AS SETTLEMANTDUEAMT
     , SETTLEMENTAMT AS SETTLEAMT
     , PAYMENTAMT
     , REFUNDAMT
     , SETTLEMENTDUEDATE
     , BUYERFEE
     , SELLERFEE
     , RESSENDER
     , RESTRANSACTIONSEQNO
     , RESRECEIVER
     , RESTRANSACTIONNO
     , RESTRANSACTIONDATE
     , RESUSERFIELD
     , RESTRANSACTIONTIME
     , RESRESPONSECODE
     , RESRESPONSEMESSAGE
     , RESORDERNO
     , RESCONTRACTDATE
  FROM [DOB2B-SERVER].[DoB2B].[dbo].KIBO_XML_K311 X WITH (NOLOCK)
 INNER JOIN DBO.CT_HEADER C WITH (NOLOCK) ON C.CTNO = X.ORDERNO
 WHERE C.CTNO NOT IN (SELECT ORDERNO FROM DBO.RECEIVE_XML_K311 WITH (NOLOCK));
GO

-- #028 세금계산서담당자

UPDATE DBO.COMPANY
   SET MPTAX_USER_NM = ''
     , MPTAX_EMAIL = '';
GO

UPDATE C
   SET C.MPTAX_USER_NM = P.PRS_NAME
     , C.MPTAX_EMAIL   = P.PRS_EMAIL
  FROM DBO.COMPANY C 
 INNER JOIN [DOB2B-SERVER].[DoB2B].[dbo].PERSON P ON P.CPY_ID = C.CPY_ID AND P.PRF_ID = 7 AND P.PRS_EMAIL <> '';
GO

UPDATE C
   SET C.MPTAX_USER_NM = P.PRS_NAME
     , C.MPTAX_EMAIL   = P.PRS_EMAIL
  FROM DBO.COMPANY C 
 INNER JOIN [DOB2B-SERVER].[DoB2B].[dbo].PERSON P ON P.CPY_ID = C.CPY_ID AND P.PRF_ID = 2 AND P.PRS_EMAIL <> ''
 WHERE C.MPTAX_EMAIL = '';
GO

UPDATE C
   SET C.MPTAX_USER_NM = '담당자'
     , C.MPTAX_EMAIL   = P.CPY_EMAIL
  FROM DBO.COMPANY C 
 INNER JOIN [DOB2B-SERVER].[DoB2B].[dbo].COMPANY P ON P.CPY_ID = C.CPY_ID AND P.CPY_EMAIL <> ''
 WHERE C.MPTAX_EMAIL = '';
GO

-- #029 MP세금계산서

SET IDENTITY_INSERT DBO.T_BILL_TB ON;
GO

WITH RankedBills AS (
    SELECT 
        B.SBILL_SEQ AS BILL_SEQ,
        'MPONE' AS BILL_SENDER_KEY,
        4 AS BILL_STATUS,
        '' AS INVOICE_KEY,
        C.CPY_ID,
        B.BILL_DT AS WRITE_DATE,
        1 AS ISSUE_DIRECTION,
        1 AS INVOICE_TYPE,
        1 AS TAX_TYPE,
        CASE WHEN B.BILL_GUBUN = '01' THEN 1 ELSE 2 END AS PURPOSE_TYPE,
        ' ' AS MODIFY_CODE,
        B.PAY_SUM_AMOUNT AS AMT,
        B.PAY_SUM_TAX AS TAX,
        B.PAY_SUM_AMOUNT + B.PAY_SUM_TAX AS TOTAL_AMT,
        B.SCOMP_VENDERNO AS INVOICER_CORP_NUM,
        B.SCOMP_NAME AS INVOICER_CORP_NAME,
        B.SCOMP_CEO AS INVOICER_CEO_NAME,
        S.ADDR + ' ' + S.ADDR2 AS INVOICER_ADDR,
        S.BUSINESS_TYPE AS INVOICER_BIZ_TYPE,
        S.INDUSTRY AS INVOICER_BIZ_CLASS,
        '담당자' AS INVOICER_CONTACT_NAME,
        NULL AS INVOICER_TEL,
        NULL AS INVOICER_HP,
        NULL AS INVOICER_EMAIL,
        B.RCOMP_VENDERNO AS INVOICEE_CORP_NUM,
        B.RCOMP_NAME AS INVOICEE_CORP_NAME,
        B.RCOMP_CEO AS INVOICEE_CEO_NAME,
        R.ADDR + ' ' + R.ADDR2 AS INVOICEE_ADDR,
        R.BUSINESS_TYPE AS INVOICEE_BIZ_TYPE,
        R.INDUSTRY AS INVOICEE_BIZ_CLASS,
        C.MPTAX_USER_NM AS INVOICEE_CONTACT_NAME,
        NULL AS INVOICEE_TEL,
        NULL AS INVOICEE_HP,
        C.MPTAX_EMAIL AS INVOICEE_EMAIL,
        0 AS REG_ID,
        B.TRANS_SUC_DATE AS REG_DT,
        NULL AS DROP_ID,
        NULL AS DROP_DT,
        B.BILL_NO AS REMARK,
        ISNULL(H.CTID, 0) AS CTID,
        ROW_NUMBER() OVER (PARTITION BY B.SBILL_SEQ ORDER BY B.BILL_DT DESC) AS RN
    FROM [DOB2B-SERVER].[DoB2B].[dbo].BILL_MASTER B WITH (NOLOCK)
    INNER JOIN DBO.COMPANY_MPFEE_INFO_TB S WITH (NOLOCK) ON S.CPY_ID = B.SCOMP_EMP_ID
    INNER JOIN DBO.COMPANY_MPFEE_INFO_TB R WITH (NOLOCK) ON R.CPY_ID = B.RCOMP_EMP_ID
    LEFT JOIN DBO.COMPANY C WITH (NOLOCK) ON C.CPY_BUSINESS_NO = B.RCOMP_VENDERNO
    LEFT JOIN DBO.CT_HEADER H WITH (NOLOCK) ON H.CTNO = B.BILL_NO
    WHERE B.SCOMP_VENDERNO IN ('4108711758', '1198194650', '1138501748')
      AND B.BILL_DT >= '20200101'
      AND B.BILL_DT < '20250401'
)
INSERT INTO DBO.T_BILL_TB (
    BILL_SEQ,
    BILL_SENDER_KEY,
    BILL_STATUS,
    INVOICE_KEY,
    CPY_ID,
    WRITE_DATE,
    ISSUE_DIRECTION,
    INVOICE_TYPE,
    TAX_TYPE,
    PURPOSE_TYPE,
    MODIFY_CODE,
    AMT,
    TAX,
    TOTAL_AMT,
    INVOICER_CORP_NUM,
    INVOICER_CORP_NAME,
    INVOICER_CEO_NAME,
    INVOICER_ADDR,
    INVOICER_BIZ_TYPE,
    INVOICER_BIZ_CLASS,
    INVOICER_CONTACT_NAME,
    INVOICER_TEL,
    INVOICER_HP,
    INVOICER_EMAIL,
    INVOICEE_CORP_NUM,
    INVOICEE_CORP_NAME,
    INVOICEE_CEO_NAME,
    INVOICEE_ADDR,
    INVOICEE_BIZ_TYPE,
    INVOICEE_BIZ_CLASS,
    INVOICEE_CONTACT_NAME,
    INVOICEE_TEL,
    INVOICEE_HP,
    INVOICEE_EMAIL,
    REG_ID,
    REG_DT,
    DROP_ID,
    DROP_DT,
    REMARK,
    CTID
)
SELECT 
    BILL_SEQ,
    BILL_SENDER_KEY,
    BILL_STATUS,
    INVOICE_KEY,
    CPY_ID,
    WRITE_DATE,
    ISSUE_DIRECTION,
    INVOICE_TYPE,
    TAX_TYPE,     
    PURPOSE_TYPE,
    MODIFY_CODE,
    AMT,
    TAX,
    TOTAL_AMT,
    INVOICER_CORP_NUM,
    INVOICER_CORP_NAME,
    INVOICER_CEO_NAME,
    INVOICER_ADDR,
    INVOICER_BIZ_TYPE,
    INVOICER_BIZ_CLASS,
    INVOICER_CONTACT_NAME,
    INVOICER_TEL,
    INVOICER_HP,
    INVOICER_EMAIL,
    INVOICEE_CORP_NUM,
    INVOICEE_CORP_NAME,
    INVOICEE_CEO_NAME,
    INVOICEE_ADDR,
    INVOICEE_BIZ_TYPE,
    INVOICEE_BIZ_CLASS,
    INVOICEE_CONTACT_NAME,
    INVOICEE_TEL,
    INVOICEE_HP,
    INVOICEE_EMAIL,
    REG_ID,
    REG_DT,
    DROP_ID,
    DROP_DT,
    REMARK,
    CTID
FROM RankedBills
WHERE RN = 1;
GO

SET IDENTITY_INSERT DBO.T_BILL_TB OFF;
GO

-- #029 MP세금계산서품목

INSERT INTO DBO.T_BILL_ITEM_TB (
       BILL_SEQ
     , PURCHASEEXPIRY
     , ITEM_NM
     , INFORMATION
     , UNIT
     , UNIT_PRICE
     , AMOUNT
     , TAX
       ) 
SELECT A.SBILL_SEQ
     , A.ITEM_DT
	 , A.ITEM_NAME
	 , '-'
	 , ISNULL(A.ITEM_UNIT, 1) 
	 , ISNULL(A.ITEM_PRICE, A.ITEM_AMOUNT)
	 , A.ITEM_AMOUNT
	 , A.ITEM_TAX
  FROM [DOB2B-SERVER].[DoB2B].[dbo].BILL_ITEM A WITH (NOLOCK)
 INNER JOIN DBO.T_BILL_TB T WITH (NOLOCK) ON T.BILL_SEQ = A.SBILL_SEQ
 WHERE A.SBILL_SEQ NOT IN (SELECT BILL_SEQ FROM DBO.T_BILL_ITEM_TB WITH (NOLOCK));
 GO

-- #030 UNUSUAL_TRANSACTION

SET IDENTITY_INSERT DBO.UNUSUAL_TRANSACTION ON;
GO

INSERT INTO DBO.UNUSUAL_TRANSACTION ([SEQ], [SECTION], [CTNO], [CPYBUYER], [CPYSELLER], [CONTENT], [WRITETIME], [PAY_ID], [USE_YN], [USE_TIME], [USE_ID], [PRO_RESULT], [CTID], [SBILL_SEQ], [LOANTYPE], [ETC])
SELECT [SEQ], [SECTION], [CTNO], [CPYBUYER], [CPYSELLER], [PRO_RESULT], [WRITETIME], [PAY_ID], [USE_YN], [USE_TIME], [USE_ID], '', [CTID], ISNULL([SBILL_SEQ], 0), [LOANTYPE], [ETC]
  FROM [DOB2B-SERVER].[DoB2B].[dbo].UNUSUAL_TRANSACTION WITH (NOLOCK)
 WHERE SEQ NOT IN (SELECT SEQ FROM DBO.UNUSUAL_TRANSACTION WITH (NOLOCK))
   AND CTID IN (SELECT CTID FROM DBO.CT_HEADER WITH (NOLOCK));

SET IDENTITY_INSERT DBO.UNUSUAL_TRANSACTION ON;
GO

-- #031 판매사사전검증해제
UPDATE C
   SET SELLER_CLEAR_YN = 'Y'
     , SELLER_CLEAR_DT = X.REGDT
 INNER JOIN [DOB2B-SERVER].[DoB2B].[dbo].[XML_A211_TB] X ON X.CPY_ID = C.CPY_ID AND X.SELLERCLEARYN = 'Y';
GO

-- #032 판매사모바일승인
UPDATE DBO.COMPANY
   SET MOBILE_YN = 'Y'
 WHERE CPY_ID IN (
SELECT CPY_ID
  FROM [DOB2B-SERVER].[DoB2B].[dbo].PERSON WITH (NOLOCK)
 WHERE PRS_APP_YN = 'Y'
       );
GO

-- #033 월합세금계산서
UPDATE C
   SET C.MPTAX_MONTH_USE_YN = 'Y'
     , C.MPTAX_MONTH_USE_ID = 0
     , C.MPTAX_MONTH_USE_DT = CAST(STUFF(STUFF(STUFF(STUFF(STUFF(A.MPTAX_USE_TIME, 5, 0, '-'), 8, 0, '-'), 11, 0, ' '), 14, 0, ':'), 17, 0, ':') AS SMALLDATETIME)
  FROM DBO.COMPANY C 
 INNER JOIN [DOB2B-SERVER].[DoB2B].[dbo].COMPANY_ADD A ON A.CPY_ID = C.CPY_ID
 WHERE A.MPTAX_USE_YN = 'Y';
 GO

-- #034 종이세금계산서이용업체
-- TO-DO

