package legacy;

import java.util.HashMap;
import java.util.Map;

import kr.co.funology.fw.mgr.ConfigurationMgr;

public class EnumData {

  public static final int longNull = -9999;
  public static final double doubleNull = -9999.0D;
  public static final String A211 = "A211";
  public static final String B211 = "B211";
  public static final String B213 = "B213";
  public static final String B215 = "B215";
  public static final String C211 = "C211";
  public static final String C213 = "C213";
  public static final String C215 = "C215";
  public static final String C221 = "C221";
  public static final String C223 = "C223";
  public static final String C225 = "C225";
  public static final String C227 = "C227";
  public static final String D211 = "D211";
  public static final String D215 = "D215";
  public static final String E211 = "E211";
  public static final String F211 = "F211";
  public static final String F221 = "F221";
  public static final String F225 = "F225";
  public static final String H211 = "H211";
  public static final String H215 = "H215";
  public static final String K231 = "K231";
  public static final String K233 = "K233";
  public static final String K235 = "K235";
  public static final String L211 = "L211";
  public static final String L213 = "L213";
  public static final String L215 = "L215";
  public static final String M211 = "M211";
  public static final String M213 = "M213";
  public static final String M215 = "M215";
  public static final String M221 = "M221";
  public static final String M225 = "M225";
  public static final String CM00 = "CM00";
  public static final String BB10 = "BB10";
  public static final String BB13 = "BB13";
  public static final String BB15 = "BB15";
  public static final String COMM = "COMM";
  public static final String K311 = "K311";
  public static final String K312 = "K312";
  public static final String K315 = "K315";
  public static final String K316 = "K316";
  public static final String K321 = "K321";
  public static final String K322 = "K322";
  public static final String B311 = "B311";
  public static final String B312 = "B312";
  public static final String A185 = "A185";
  public static final String A186 = "A186";
  public static final String A181 = "A181";
  public static final String A182 = "A182";
  public static final String C211_OK = ",C221,C227,";
  public static final String C221_OK = ",C223,C225,D211,";
  public static final String C223_OK = ",C223,";
  public static final String C225_OK = ",C221,";
  public static final String D211_OK = ",D215,E211,";
  public static final String E211_OK = ",F211,H211,H215,";
  public static final String F221_OK = ",F225,H211,";
  public static final String H211_OK = ",H215,";
  public static final String GRT_APPLICATION_NO = "001";
  public static final String TRANS_SEQ_NO = "002";
  public static final String TRADE_SEQ_NO = "003";
  public static final String CASH_SEQ_NO = "004";
  public static final String FIRST_CASH = "C";
  public static final String FIRST_GRT = "TH";
  public static final String MPCODE = ConfigurationMgr.getInstance().getString("OWNER_MPCODE");
  public static final String KCGFCODE = "0760000";
  public static final String KIBOCODE = "0770000";
  public static final String MP_APPLICATION_STATUS = "010";
  public static final String KCGF_APPLICATION_STATUS = "020";
  public static final String REGIST_STATUS = "030";
  public static final String APRROVAL_STATUS = "040";
  public static final String ISSUE_NO_STATUS = "045";
  public static final String ISSUE_STATUS = "050";
  public static final String CLEAR_STATUS = "080";
  public static final String CANCEL_STATUS = "090";
  public static final String GRT_TYPE = "02";
  public static final String PER_GRT_TYPE = "01";
  public static final String ISS = "ISS";
  public static final String RCV = "RCV";
  public static final String CHGTYPE10 = "10";
  public static final String CHGTYPE20 = "20";
  public static final String CHGTYPE30 = "30";
  public static final String CHGTYPE40 = "40";
  public static final String CHGTYPE90 = "90";
  public static final String SYS_BIGBEAM = "이엠투";
  public static final String SYS_KIBO = "기술보증기금";
  public static final String SUCCESS = "1";
  public static final String FAIL = "0";

  public static final Map<String, String> getStatusDesc() {
    Map<String, String> map = new HashMap<>();
    map.put("010", "MP신청");
    map.put("020", "기금신청");
    map.put("030", "접수");
    map.put("040", "승인");
    map.put("050", "발급");
    map.put("080", "해지");
    map.put("090", "취소");
    return map;
  }

  public static final Map<String, String> getTransactionnoDesc() {
    Map<String, String> map = new HashMap<>();
    map.put("A211", "회원 및 한도조회");
    map.put("B211", "매매계약서신규");
    map.put("B213", "매매계약서변경");
    map.put("B215", "매매계약서취소");
    map.put("C211", "보증신청신규");
    map.put("C213", "보증신청변경");
    map.put("C215", "보증신청취소");
    map.put("C221", "보증접수통지");
    map.put("C223", "보증접수변경");
    map.put("C225", "보증접수취소");
    map.put("C227", "보증진행취소통지");
    map.put("D211", "보증승인통지");
    map.put("D215", "보증승인취소");
    map.put("E211", "보증서발급");
    map.put("F221", "조건변경통지");
    map.put("F225", "조건변경통지취소");
    map.put("H211", "보증해지");
    map.put("H215", "보증해지취소");
    map.put("K231", "결제신규");
    map.put("K233", "결제변경");
    map.put("K235", "결제취소");
    map.put("L211", "배송전송");
    map.put("L213", "배송변경");
    map.put("L215", "배송취소");
    map.put("M211", "어음발행");
    map.put("M213", "어음발행변경");
    map.put("M215", "어음발행취소");
    map.put("M221", "어음수취");
    map.put("M225", "어음수취취소");
    map.put("CM00", "공통전문");
    map.put("BB10", "MP보증신청");
    map.put("BB13", "MP보증변경");
    map.put("BB15", "MP보증취소");
    return map;
  }
}
