sURL=http://210.112.124.64:7014/xerc/soaptoserver
#kibo_sURL=http://210.112.124.3:7770/mps/Send/xmlKiboJavaToSend.jsp
#kibo_yun_sURL=http://210.112.124.3:7770/mps/Send/xmlKoregJavaToSend.jsp
timeout=60000
dn-value=cn=\uC6F0\uCEA0\uD504\uC8FC\uC2DD\uD68C\uC0AC,ou=SERVER,ou=KICA,ou=SERVER,ou=licensedCA,o=KICA,c=KR
dn-password=well0413**
